### ISSUE TITLE
shock tests in 2D and 3D

### ISSUE THREAD

**Issue by junghans** [laristra/flecsph#12]

**Comment by sagert** [comment]
Hi Christoph, 

sorry, I don't quite get it. Can you tell me the details of the problem to fix?

**Comment by korobkin** [comment]
Hi Irina,
Christoph was just showing me the Projects feature and we accidentally assigned this to you. I am sorry for the confusion! I am going to delete this issue. It was just to demonstrate how to use the Projects and how it's such a great tool for organizing shared work.
