### ISSUE TITLE
Dockerfile: Flecsi on Fedora

### ISSUE THREAD

**Issue by JulienLoiseau** [laristra/flecsph#8]
FleCSI not compiling on Travis due to g++ and pthread:

g++: error: unrecognized command line option '-pthread -Dpthread -D-DOMPI_SKIP_MPICXX -D-DMPICH_SKIP_MPICXX'

Any hints ? 
In refactor branch of FleCSPH.

**Comment by junghans** [comment]
There are quotes around `-pthread -Dpthread -D-DOMPI_SKIP_MPICXX -D-DMPICH_SKIP_MPICXX` and hence it interprets it as one option.

**Comment by junghans** [comment]
I think that is an issue in cinch! @tuxfan, @charest any idea?

**Comment by charest** [comment]
I had to do it here to get arround that issue:
https://github.com/laristra/flecsale/blob/stable/cmake/run_test.cmake#L30
